name: On Tag Creation

on:
  push:
    paths:
      - "CHANGELOG.md"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Print Changelog Change and Latest Tag
        run: |
          echo "CHANGELOG.md was updated!"
          echo "The latest tag is: ${{ env.latest_tag }}"
