name: On Tag Creation

on:
  push:
    tags:
      - "v*" # Adjust this pattern if your releases use a different format

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get the Tag Name
        run: |
          echo "New tag pushed: ${{ github.ref_name }}"
