name: On Push
on:
  push:
    branches:
      - 'main'

jobs:
  validate_push:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{inputs.package_dir}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls
          echo "Something is happening on ${{github.ref_name}}"
