on:
  push:
    branches:
      - 'flux-release'

jobs:
  validate_push:
    if: "!contains(github.event.head_commit.message || '', '[deleted]')" # Skip on branch delete
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Something is happening"
