name: On Push
on:
  push:
    branches:
      - main

jobs:
  validate_push:
    # if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simple Message
        # if: github.actor != 'github-actions'
        run: |
          ls
          echo "Something is happening on ${{github.ref_name}} by ${{github.actor}}"
