name: On Push
on:
  push:
    branches:
      - 'flux-release'
  workflow_dispatch:
    inputs:
      package_dir:
        description: 'Directory of the package'
        required: true
        type: string

jobs:
  validate_push:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{inputs.package_dir}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls
          echo "Something is happening on ${{github.ref_name}}"
