name: Only Owners
on: 
  workflow_dispatch:
jobs:
  print-data:
    runs-on: ubuntu-latest
    name: Print data if admin
    steps:
      - name: Print Name
        run: echo "{{github.repository_owner}}"