name: Only Owners
on: 
  workflow_dispatch:
jobs:
  print-data:
    runs-on: ubuntu-latest
    name: Print data if admin
    steps:
      - name: Print Name
        run: echo "{{github.repository_owner}}"
      - name: Get Latest Release
        id: latest-release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const isTag = context.ref.includes('tag');
            let response = {};
            if (isTag) {
              const tag = context.ref.replace('refs/tags/', '');
              response = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag
              })
            } else {
              response = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              })
            }
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "${{ github.event.repository.name }} test pr",
              head: "test",
              base: "main",
              body: response.data.body,
              draft: true
            });

            console.log(`Created PR #${pullRequest.number}: ${pullRequest.html_url}`);

            // Set outputs
            core.setOutput("pull-request-number", pullRequest.number);
            core.setOutput("pull-request-url", pullRequest.html_url);
            return JSON.stringify(response.data);
